version: '3.1'

services:
  postgres:
    container_name: postgres_container
    image: postgres:13
    env_file:
      - src/main/docker/db.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/corpo-event/data
  quarkus:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080

volumes:
  postgres-data: