version: '3.1'

services:
  corpo-app_postgres:
    container_name: corpo-app_postgres_container
    image: postgres:13
    env_file:
      - src/main/docker/db.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    hostname: postgres
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      - corpo-app_postgres-data:/var/lib/postgresql/corpo-event/data

  corpo-app_quarkus:
    build:
      context: .
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
    depends_on:
      - corpo-app_postgres

volumes:
  corpo-app_postgres-data: